### PR TITLE
PR for Issue #63 (replace conda with pip)

### PR DESCRIPTION
**Pull request by bhargavkakadiya**
This addresses #63

Adding two new files:
1) README-vf.md : The file is carried forward from the original readme to reflect changes on usage with fish shell and virtual fish
2) requirements.txt

### CODE REVIEW

**Comment by trentmc** [comment]
Thanks for the PR,!

For #63 the added requirements.txt s a start. To minimize confusion it is better if all the work for #63 is done at once, before merging this pr.

Second, what's "fish"?

Finally, adding a whole second readme that is 99% identical to the original violates DRY (Don't Repeat Yourself) principle, and hurts maintainability. Eg does exhibition change to the original readme need to get repeated in the alternate readme?

Ideally there is just one "big fat default path" that the majority of devs can use out of the box.  Moving from conda to pip as #63 discusses is a good direction.

**Comment by bhargavkakadiya** [comment]
Thanks for the comments, Trent

Just created this PR to address #52 which was a high priority, but probably, I should have just linked my fork.

And, Fish is a command-line shell https://fishshell.com/ and it has 'virtual fish' as environment manager, quite a standard practice at LTF.

Got the DRY principle, we can just link the issue in README if required.

**Comment by trentmc** [comment]
Thanks for the info.

> Just created this PR to address #52 which was a high priority, but probably, I should have just linked my fork.

I feel like I'm missing something. #52 has several changes needed, I don't see how this PR works.

#52 will be solved only when the code is in the 'main' trunk, not by linking a fork. If we just linked forks everywhere the codebase would be unusable.

> Fish is a command-line shell https://fishshell.com/ and it has 'virtual fish' as environment manager, quite a standard practice at LTF.

Thanks. Sure. The current README will work for any console, whether bash, fish or whatever, no? 


--

To set expectations: To solve a specific issue, do a specific PR.  Do the _complete_ solution in the PR. Keep changes in the PR restricted to solving _just_ that issue. Find ways to keep things simple, including DRY. If you see the need to refactor prior, so that the final changes are clean, then ideally do a separate PR first, which keeps functionality identical.

**Comment by bhargavkakadiya** [comment]
The recent commits checks #63 ToDos.

**Comment by trentmc** [comment]
Thanks for making the changes in line with my suggestions, and checking off the TODOs given in #63. 

I have been testing locally, but without success. The problem is pipenv. Installation and more. I've been working to resolve it, but it seems that the problem is pipenv itself. It's simply not stable.
- "Pipenv: promises a lot, delivers very little" -- [link](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/)
- "Frequently encountered pipenv problems" -- [link](https://pipenv-fork.readthedocs.io/en/latest/diagnose.html)

This ticket is about moving away from conda to avoid issues, including installation and interaction with other sw. Using pipenv also has issues, they seem to be even worse than conda. 

The original idea was to move conda -> pip. I strongly prefer that we use good old pip. (With python3 that has built-in virtualenv). Stable, widely used, they just work. We've had good experience with this combination most recently in the Ocean repos that use Python: ocean.py, aquarius, provider.

@bhargavkakadiya would you like to make the changes moving this to pip? Or, I can.

FYI https://github.com/oceanprotocol/ocean.py has good pattern of how to have it all set up.

**Comment by bhargavkakadiya** [comment]
Thank you @trentmc for reviewing and suggesting the next steps.
I would make the changes in line with the pip and virtualenv.

**Comment by bhargavkakadiya** [comment]
I am running into some issues using venv on the fish shell, testing on it doesn't seem generalized.
Perhaps, @trentmc would you like to continue on this?
Thank You

**Review by trentmc — APPROVED** [review]
Looks great! I tested too. Merging.

**Pull request merged**
