### PR TITLE
v4 drivers, engine, v4agents 

### PR DESCRIPTION
**Pull request by trangnv**
NOTE: this is a very old PR, it ran into issues and will not be used. To resolve the issues, we have done a bunch of other work: use brownie / remove middleware drivers, add v4 contracts, start writing v4 tests, clean up oceanv3 code & tests. We're only keeping around this PR for now, as some changes may be inspiration for v4 work. At some point we will delete this PR. But not yet. --trent 20211202

----

toward #29

### CODE REVIEW

**Comment by trentmc** [comment]
I've been trying to reproduce a flow using hardhat end-to-end for an oceanv4 version of "test_btoken.py".

I've been documenting the flow. Check the recent commits to the PR by me. Mostly changes to the docs, but do note a few other tweaks too.

I'm not there yet though. Current bug is the following. If you see a way to help @trangnv that would be great:)

Note for the rest of the day, I need to jump into calls. Back at it later:)

```text
pytest drivers_oceanv4/test/test_btoken.py 
================================================== test session starts ===================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/trentmc/code/tokenspice, configfile: pytest.ini
plugins: web3-5.24.0
collected 0 items / 1 error                                                                                              

========================================================= ERRORS =========================================================
__________________________________ ERROR collecting drivers_oceanv4/test/test_btoken.py __________________________________
ImportError while importing test module '/home/trentmc/code/tokenspice/drivers_oceanv4/test/test_btoken.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
drivers_oceanv4/test/test_btoken.py:1: in <module>
    from drivers_oceanv4 import btoken, datatoken, dtfactory
drivers_oceanv4/btoken.py:6: in <module>
    from drivers_oceanv4.contract_base import ContractBase
drivers_oceanv4/contract_base.py:16: in <module>
    from drivers_oceanv4.contract_utils import (
drivers_oceanv4/contract_utils.py:12: in <module>
    from assets.contracts import artifacts
E   ModuleNotFoundError: No module named 'assets.contracts'
================================================ short test summary info =================================================
ERROR drivers_oceanv4/test/test_btoken.py
```

**Comment by trangnv** [comment]
Thank you @trentmc 
The workflow is clean and neat. I should have done it when deployed v4 contracts.
Anyway, I will dig into `test_btoken` today.

**Comment by trangnv** [comment]
`drivers_oceanv4/test/test_btoken.py::test_OCEAN` should work now.
- I didn't use web3util.py but use `contract_utils.py` copied from ocean.py
But thanks to the commit on web3util earlier the `abiFilename` searches through subdirectories to find the path, this is the most painful part for me last week since I didn't know where to look for artifacts.
- Will update those utils changes in v4 netlist about file

**Comment by trentmc** [comment]
Hey Trang - let's have a chat on this PR. I just sent you an invite.

**Comment by trentmc** [comment]
A bunch of newer work has been done. We can safely close this PR.

**Pull request closed without merging**
