### PR TITLE
Test oceanv4 

### PR DESCRIPTION
**Pull request by trangnv**
toward #111 

branch: [`test_oceanv4`](https://github.com/tokenspice/tokenspice/tree/test_oceanv4)

### CODE REVIEW

**Comment by trangnv** [comment]
```python
DT.deployPool(
        pool_create_data["ssParams"],
        pool_create_data["swapFees"],
        pool_create_data["addresses"],
        {"from":account0}
    )
```
hasn't successful yet. Something is wrong with `pool_create_data`

**Comment by trangnv** [comment]
- Not sure if unsuccessful installing `brownie pm install nomiclabs/hardhat@2.7.0` would cause problem later
- A work around: Because `Bpool.sol` and `FactoryRouter.sol` only use `console.sol` from hardhar library, so I copied that file into `sol080/contracts/oceanv4/hardhat`
- Compiled successfully

**Comment by trangnv** [comment]
`test_erc721_factory` has problem we have faced before: 
- separated test runs successfully 
- if run all test, test_createBPool_via_util fails

**Comment by trangnv** [comment]
Units test for oceanv4 contracts is almost done, I'm working on other branch for oceanv4 netlist, getting pool created and interact with it. Might need to loop back and fix oceanv4util

**Review by trentmc — APPROVED** [review]

**Pull request merged**
